modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "unclamped"
version = "${version}"
displayName = "Create: Unclamped"
authors = "TechTastic"
description = '''
Removes the various clamps on speed!
'''
#logoFile = ""

[[dependencies.unclamped]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unclamped]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.unclamped]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "AFTER"
side = "BOTH"